version: '3'
services:
  api-gateway:
    build:
      context: ./api-gateway 
      dockerfile: Dockerfile 
    ports:
      - "8082:8082" 

  order-service:
    build:
      context: ./order-service 
      dockerfile: Dockerfile 
    ports:
      - "8081:8081" 