server.port: 8081

spring.datasource:
  url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  username: sa
  password: password

spring:
  h2:
    console:
      enabled: true


gateway.url: 'http://localhost:8082/processOrder'

